### ISSUE TITLE
AssertionError but don't know why

### ISSUE THREAD

**Issue by netAction** [NiklasRosenstein/movrepair#3]
I tried to repair a file from Insta360 X2 but movrepair crashs. Python 3, Windows 11.

>python movrepair.py VID_20220605_135052_00_024.insv --repair VID_20220605_134145_00_023.insv
Output file: VID_20220605_134145_00_023-fixed.insv
Traceback (most recent call last):
  File "C:\Users\schmi\OneDrive\Desktop\Videoretten\movrepair.py", line 277, in <module>
    sys.exit(main())
  File "C:\Users\schmi\OneDrive\Desktop\Videoretten\movrepair.py", line 267, in main
    return repair_file(reference, broken, output, do_fix_metadata=not args.no_fix_metadata)
  File "C:\Users\schmi\OneDrive\Desktop\Videoretten\movrepair.py", line 186, in repair_file
    for atom in MovAtomR.make_root(reference).iter_atoms():
  File "C:\Users\schmi\OneDrive\Desktop\Videoretten\movio.py", line 146, in iter_atoms
    atom.skip()
  File "C:\Users\schmi\OneDrive\Desktop\Videoretten\movio.py", line 129, in skip
    assert nbytes >= 0
AssertionError

**Comment by HanalogInstruments** [comment]
Look like your files doesn't have moov atom, try to use hxd editor and find "mdat" and "moov"
