### ISSUE TITLE
 EOF while reading atom data

### ISSUE THREAD

**Issue by Jaime02** [NiklasRosenstein/movrepair#4]
Hello, I'm trying to repair a mov video and I have got this error:

Traceback:
```
C:\Users\jaime\Downloads\movrepair-master>python movrepair.py RE.MOV --repair DA.MOV
Output file: DA-fixed.MOV
Traceback (most recent call last):
  File "C:\Users\jaime\Downloads\movrepair-master\movrepair.py", line 277, in <module>
    sys.exit(main())
  File "C:\Users\jaime\Downloads\movrepair-master\movrepair.py", line 267, in main
    return repair_file(reference, broken, output, do_fix_metadata=not args.no_fix_metadata)
  File "C:\Users\jaime\Downloads\movrepair-master\movrepair.py", line 194, in repair_file
    atom = atom.to_atomd()
  File "C:\Users\jaime\Downloads\movrepair-master\movio.py", line 165, in to_atomd
    return MovAtomD(self.tag, self.read_data(), parent=parent)
  File "C:\Users\jaime\Downloads\movrepair-master\movio.py", line 109, in read_data
    raise MovFileError('reached EOF while reading "{}" atom data'.format(
movio.MovFileError: reached EOF while reading "♣♠9" atom data
```
OS: Windows 11
Python: 3.9

What can I do? Thanks in advance

**Comment by HanalogInstruments** [comment]
> Hello, I'm trying to repair a mov video and I have got this error:
> 
> Traceback:
> 
> ```
> C:\Users\jaime\Downloads\movrepair-master>python movrepair.py RE.MOV --repair DA.MOV
> Output file: DA-fixed.MOV
> Traceback (most recent call last):
>   File "C:\Users\jaime\Downloads\movrepair-master\movrepair.py", line 277, in <module>
>     sys.exit(main())
>   File "C:\Users\jaime\Downloads\movrepair-master\movrepair.py", line 267, in main
>     return repair_file(reference, broken, output, do_fix_metadata=not args.no_fix_metadata)
>   File "C:\Users\jaime\Downloads\movrepair-master\movrepair.py", line 194, in repair_file
>     atom = atom.to_atomd()
>   File "C:\Users\jaime\Downloads\movrepair-master\movio.py", line 165, in to_atomd
>     return MovAtomD(self.tag, self.read_data(), parent=parent)
>   File "C:\Users\jaime\Downloads\movrepair-master\movio.py", line 109, in read_data
>     raise MovFileError('reached EOF while reading "{}" atom data'.format(
> movio.MovFileError: reached EOF while reading "♣♠9" atom data
> ```
> 
> OS: Windows 11 Python: 3.9
> 
> What can I do? Thanks in advance

Could you upload your files here via gofile.io?

**Comment by Jaime02** [comment]
> Could you upload your files here via gofile.io?

Sorry, I deleted the corrupted mov file since it was huge 🤓
